//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKPolizaGastos.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConceptosNominas
    {
        public int IdConcepto { get; set; }
        public Nullable<int> IdNomina { get; set; }
        public string ClaveProdServ { get; set; }
        public string Cantidad { get; set; }
        public string ClaveUnidad { get; set; }
        public string Descripcion { get; set; }
        public string ValorUnitario { get; set; }
        public string Importe { get; set; }
        public string Descuento { get; set; }
        public string UUID { get; set; }
        public string NumEmpleado { get; set; }
        public Nullable<System.DateTime> FechaConvert { get; set; }
    }
}
