//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKPolizaGastos.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diot
    {
        public int IdDiot { get; set; }
        public string RFC { get; set; }
        public string Proveedor { get; set; }
        public Nullable<decimal> Iva_Trasladado { get; set; }
        public Nullable<decimal> Base { get; set; }
        public Nullable<decimal> Iva_Trasladado_Calculado { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<int> Periodo { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
    }
}
