//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKPolizaGastos.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactEmi_RFCMesAño
    {
        public int IdFactura { get; set; }
        public string Serie { get; set; }
        public string Folio { get; set; }
        public string Fecha { get; set; }
        public string SubTotal { get; set; }
        public string IVA { get; set; }
        public string Total { get; set; }
        public string Receptor { get; set; }
        public string RFCReceptor { get; set; }
        public string UUID { get; set; }
        public Nullable<int> Año { get; set; }
        public Nullable<int> Mes { get; set; }
    }
}
