//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKPolizaGastos.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Localidades
    {
        public int IdLocalidad { get; set; }
        public string Localidad { get; set; }
        public string Sigla_Sucursal { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string Departamento { get; set; }
    
        public virtual Empresas Empresas { get; set; }
    }
}
