//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKPolizaGastos.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotasPagoPolizaUnoAuno
    {
        public int notaDePagoId { get; set; }
        public string Factura { get; set; }
        public Nullable<int> Contrato { get; set; }
        public Nullable<decimal> Debe { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> Iva { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Estatus { get; set; }
        public Nullable<System.DateTime> FechaFact { get; set; }
        public string Caja { get; set; }
        public string CajaLetra { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<int> Ano { get; set; }
        public string Suc { get; set; }
        public Nullable<decimal> Prestamo { get; set; }
    }
}
